export type TrainDataStoreType = {
  startDay: string;
  endDay: string;
  startTime: string;
  endTime: string;
  pay: string;
  trainType: string;
  startStation: string;
  endStation: string;
  kid: number;
  adult: number;
  startStationForView: string;
  endStationForView: string;
  startDayForView: string;
  trainTypeForView: string;
  startTimeForView: string;
  setStartDay: (type: string) => void;
  setEndDay: (type: string) => void;
  setStartTime: (type: string) => void;
  setEndTime: (type: string) => void;
  setPay: (type: string) => void;
  setTrainType: (type: string) => void;
  setStartStation: (type: string) => void;
  setEndStation: (type: string) => void;
  setKid: (type: number) => void;
  setAdult: (type: number) => void;
  setStartStationForView: (type: string) => void;
  setEndStationForView: (type: string) => void;
  setStartDayForView: (type: string) => void;
  setTrainTypeForView: (type: string) => void;
  setStartTimeForView: (type: string) => void;
};
